---
title: "workshop-09"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## welcome to workshop-09
Today we will be continue to work on the following topics:
- Github and Git
- Intro to tidyverse
  - dplyr
  - tidyr
  - ggplot2

## let's load the libraries  
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
```

  
## the data we will be working with
```{r}
# courtesy of @gregory-golden;
# noised and randomised data from flow experiments; hw8_data.csv
df <- read.csv("/Users/gregorygolden/.ssh/CSWorkshopRep/cs-workshop/workshop-08-intro-to-tidyverse/hw8_data.csv", check.names = FALSE)

head(df)
colnames(df)
```
plotting one column off the wide table format!
```{r}
ggplot(data = df, mapping = aes(x = `CD4 Tem HLA-DR+`, 
                                y = `CD8 Tem HLA-DR+`, 
                                color = `Disease Status`,
                                shape = `Sex`)) +
  geom_point() + 
  theme_classic() +
  facet_wrap(~ Tissue, nrow = 2)
```
plotting more than one column!
```{r}
dfLong <- df%>%
  select(c(1:6), starts_with("B cells")) %>%
  pivot_longer(all_of(starts_with("B cells")), names_to = "Metric", values_to = "percent")

ggplot(dfLong, aes(x = `Disease Status`, y = percent, color = `Disease Status`)) +
  geom_point(alpha = 0.5) +
  facet_wrap(~ Metric)
```

